<?php
$e = static fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
$nome = $dados['nome_destinatario'] ?? 'Colaborador(a)';
$titulo = $dados['titulo'] ?? 'Documento pendente';
$disponivelDesde = $dados['disponivel_desde'] ?? 'Data não informada';
$tempoPendente = $dados['tempo_pendente'] ?? 'Pendente';
$quantidade = $dados['quantidade_documentos'] ?? '1';
$url = $dados['url_acao'] ?? '#';
$bannerCid = $dados['banner_cid'] ?? null;
?>
<div style="margin:0;background:#f1f5f9;padding:28px 12px;font-family:Arial,sans-serif;color:#0f172a"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center"><table role="presentation" width="680" style="width:100%;max-width:680px;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden" cellspacing="0" cellpadding="0">
<?php if ($bannerCid): ?><tr><td><img src="cid:<?= $e($bannerCid) ?>" alt="Documento pendente" width="680" style="display:block;width:100%;height:auto;border:0"></td></tr><?php else: ?><tr><td style="background:#0f172a;padding:27px 30px;color:#fff"><div style="font-size:11px;letter-spacing:2px;color:#fcd34d;font-weight:bold">PORTAL INTERNO DE ASSINATURAS</div><div style="font-size:22px;font-weight:bold;margin-top:10px">Assinatura ainda pendente</div></td></tr><?php endif; ?>
<tr><td style="padding:30px"><p style="font-size:15px;line-height:1.65;margin:0">Olá, <strong><?= $e($nome) ?></strong>. O envelope abaixo continua aguardando sua assinatura.</p><div style="margin:22px 0;padding:17px;border:1px solid #fde68a;border-radius:12px;background:#fffbeb"><strong style="color:#b45309">Atenção à pendência</strong><p style="margin:7px 0 0;color:#475569;font-size:13px;line-height:1.5">O fluxo permanecerá aguardando até que você assine ou registre uma recusa justificada.</p></div>
<table role="presentation" width="100%" style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;font-size:13px" cellspacing="0" cellpadding="0"><tr><td style="padding:18px"><p style="margin:0 0 9px;color:#64748b">Envelope<br><strong style="color:#0f172a"><?= $e($titulo) ?></strong></p><p style="margin:0 0 9px;color:#64748b">Disponível desde: <strong style="color:#0f172a"><?= $e($disponivelDesde) ?></strong></p><p style="margin:0;color:#64748b">Tempo pendente: <strong style="color:#b45309"><?= $e($tempoPendente) ?></strong> &nbsp;·&nbsp; Documentos: <strong style="color:#0f172a"><?= $e($quantidade) ?></strong></p></td></tr></table>
<div style="text-align:center;margin:24px 0"><a href="<?= $e($url) ?>" style="display:inline-block;background:#d97706;color:#fff;text-decoration:none;font-size:12px;font-weight:bold;padding:15px 24px;border-radius:10px">ACESSAR PENDÊNCIA</a></div><div style="padding:15px;border-left:4px solid #d97706;background:#fffbeb;color:#92400e;font-size:12px;line-height:1.5">Se houver inconsistência, utilize a opção de recusa e informe o motivo.</div><p style="margin:25px 0 0;color:#94a3b8;font-size:11px;text-align:center;line-height:1.5">Lembrete automático da Intranet Souza.<br>Desconsidere se a assinatura já tiver sido realizada.</p></td></tr></table></td></tr></table></div>
