<?php
$e = static fn($v) => htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8');
$titulo = $dados['titulo'] ?? 'Envelope concluído';
$tipo = $dados['tipo_fluxo'] ?? 'Sequencial';
$criadoEm = $dados['criado_em'] ?? 'Não informado';
$concluidoEm = $dados['concluido_em'] ?? 'Não informado';
$documentos = $dados['documentos'] ?? [];
$assinantes = $dados['assinantes'] ?? [];
$bannerCid = $dados['banner_cid'] ?? null;
?>
<div style="margin:0;background:#f1f5f9;padding:28px 12px;font-family:Arial,sans-serif;color:#0f172a"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center"><table role="presentation" width="680" style="width:100%;max-width:680px;background:#fff;border:1px solid #e2e8f0;border-radius:18px;overflow:hidden" cellspacing="0" cellpadding="0">
<?php if ($bannerCid): ?><tr><td><img src="cid:<?= $e($bannerCid) ?>" alt="Fluxo concluído" width="680" style="display:block;width:100%;height:auto;border:0"></td></tr><?php else: ?><tr><td style="background:#0f172a;padding:27px 30px;color:#fff"><div style="font-size:11px;letter-spacing:2px;color:#6ee7b7;font-weight:bold">PORTAL INTERNO DE ASSINATURAS</div><div style="font-size:22px;font-weight:bold;margin-top:10px">Fluxo concluído com sucesso</div></td></tr><?php endif; ?>
<tr><td style="padding:30px"><p style="font-size:15px;line-height:1.65;margin:0">O envelope <strong><?= $e($titulo) ?></strong> concluiu todas as etapas de assinatura. Os documentos finais seguem anexados.</p><table role="presentation" width="100%" style="margin:22px 0;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;font-size:13px" cellspacing="0" cellpadding="0"><tr><td style="padding:18px"><p style="margin:0 0 8px;color:#64748b">Status: <strong style="color:#059669">CONCLUÍDO</strong></p><p style="margin:0 0 8px;color:#64748b">Tipo de fluxo: <strong style="color:#0f172a"><?= $e($tipo) ?></strong></p><p style="margin:0 0 8px;color:#64748b">Criado em: <strong style="color:#0f172a"><?= $e($criadoEm) ?></strong></p><p style="margin:0;color:#64748b">Concluído em: <strong style="color:#0f172a"><?= $e($concluidoEm) ?></strong></p></td></tr></table>
<h3 style="font-size:14px;margin:22px 0 8px">Documentos anexados</h3><ul style="padding-left:20px;color:#334155;font-size:13px;line-height:1.6"><?php foreach ($documentos as $doc): ?><li><?= $e($doc) ?></li><?php endforeach; ?></ul><h3 style="font-size:14px;margin:22px 0 8px">Assinaturas registradas</h3><ul style="padding-left:20px;color:#334155;font-size:13px;line-height:1.6"><?php foreach ($assinantes as $item): ?><li><strong><?= $e($item['nome'] ?? '') ?></strong><?= !empty($item['momento']) ? ' — '.$e($item['momento']) : '' ?></li><?php endforeach; ?></ul>
<div style="margin-top:24px;padding:15px;border-left:4px solid #2563eb;background:#eff6ff;color:#1e3a8a;font-size:12px;line-height:1.5">Os PDFs anexos contêm os registros de assinatura com identificação, setor, e-mail, data, hora e IP.</div><p style="margin:25px 0 0;color:#94a3b8;font-size:11px;text-align:center;line-height:1.5">Mensagem automática da Intranet Souza.<br>Não responda a este e-mail.</p></td></tr></table></td></tr></table></div>
